modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/kyleplo/curses-and-cryptics/issues"
license = "LGPL-3.0"

[[mods]]
modId = "curses_and_cryptics"
version = "${version}"
displayName = "Curses and Cryptics"
displayURL = "https://modrinth.com/mod/curses-and-cryptics"
authors = "kyleplo"
description = '''
Expansion upon Minecraft's curses and enchantment mechanics.
'''
logoFile = "assets/curses_and_cryptics/icon.png"
logoBlur = false

[[dependencies.curses_and_cryptics]]
modId = "neoforge"
type = "required"
versionRange = "[21.5,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.curses_and_cryptics]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.5,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "curses_and_cryptics.mixins.json"
