modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "curses_and_crusades"
version = "${version}"
displayName = "Curses & Crusades"
authors = "Me!"
description = '''
This is an example description! Tell everyone what your mod is about!
'''
#logoFile = ""

[[dependencies.curses_and_crusades]]
modId = "neoforge"
type = "required"
versionRange = "[21.5,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.curses_and_crusades]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.5,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "curses_and_crusades.mixins.json"
